In [13]:
import numpy as np

import copy, math
import torch
from torch import nn, optim
import torch.nn.functional as F

from torch.autograd import Variable
from torch.autograd import functional as F


In [2]:
model = nn.Sequential(nn.Linear(10, 10),
                      nn.ReLU(),
                      nn.Linear(10, 10),
                      nn.LogSoftmax(dim = 1)
                     )

# Define the loss
criterion = nn.CrossEntropyLoss()

# Define the optimizer
optimizer = optim.Adam(model.parameters(), lr = 0.001)


In [3]:
x = torch.rand(5, 10)
y = torch.randint(10, (5,))

In [4]:
out = model(x)
loss = criterion(out, y)
loss.backward()

In [5]:
model[0].weight.grad

tensor([[ 0.0243,  0.0232,  0.0168, -0.0002,  0.0342,  0.0296, -0.0038,  0.0020,
          0.0382,  0.0123],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.0283,  0.0104,  0.0184, -0.0161,  0.0157, -0.0017, -0.0410, -0.0057,
         -0.0103, -0.0236],
        [-0.0464, -0.0092, -0.0254, -0.0331, -0.0147, -0.0204, -0.0192, -0.0252,
         -0.0519, -0.0182],
        [ 0.0060, -0.0003,  0.0081, -0.0196, -0.0027, -0.0197, -0.0278, -0.0110,
          0.0144, -0.0157],
        [-0.0546, -0.0246, -0.0418, -0.0431, -0.0553, -0.0701, -0.0252, -0.0353,
         -0.0552, -0.0324],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0089,  0.0050,  0.0105,  0.0283,  0.0152,  0.0299,  0.0226,  0.0204,
          0.0038,  0.0157],
        [ 0.0185,  

In [6]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
y.grad_fn

In [7]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [8]:
Q = 3*a**3 - b**2

In [9]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [10]:
a.grad

tensor([36., 81.])

In [42]:
def XTX(X):
    return X.T @ X
inp = torch.rand(2, 2)
A = torch.rand(2, 2)
J = F.jacobian(XTX, inp)
J

tensor([[[[1.7994, 0.0000],
          [0.9090, 0.0000]],

         [[0.2644, 0.8997],
          [0.6977, 0.4545]]],


        [[[0.2644, 0.8997],
          [0.6977, 0.4545]],

         [[0.0000, 0.5288],
          [0.0000, 1.3953]]]])

In [43]:
F.vjp(XTX, inp, A)

(tensor([[1.0160, 0.5550],
         [0.5550, 0.5567]]),
 tensor([[0.8123, 0.7985],
         [0.8075, 0.7556]]))

In [44]:
A

tensor([[0.3480, 0.5575],
        [0.1465, 0.3122]])

In [45]:
(A.T + A) @ inp.T

tensor([[0.8123, 0.8075],
        [0.7985, 0.7556]])

In [46]:
inp @ (A.T + A)

tensor([[0.8123, 0.7985],
        [0.8075, 0.7556]])

In [48]:
M = torch.rand(2,2)
def MX(X):
    return M @ X
inp = torch.rand(2, 2)
A = torch.rand(2, 2)
J = F.jacobian(MX, inp)
J

tensor([[[[0.6954, 0.0000],
          [0.9645, 0.0000]],

         [[0.0000, 0.6954],
          [0.0000, 0.9645]]],


        [[[0.8849, 0.0000],
          [0.8585, 0.0000]],

         [[0.0000, 0.8849],
          [0.0000, 0.8585]]]])

In [ ]:
dec = nn.